### PR TITLE
Add text mining to phenotypic feature search

### PR DESCRIPTION
**Pull request by belkassaby**

### CODE REVIEW

**Comment by belkassaby** [comment]
new live URL: http://35.231.58.199/dashboard

**Comment by belkassaby** [comment]
new live URL: http://34.74.159.187/dashboard

**Review by ielis — CHANGES_REQUESTED** [review]
Hi @belkassaby 
as we discussed, there are few issues that need to be addressed here:
- The text mining workflow needs to be updated. The *Add approved terms* should invoke the *Start over* button, asking the user for another text
- The Phenotypic feature UI should set a default age of onset based on age of last encounter entered in the first step. The age of onset is set to phenotypic features found by text mining or through the search field.
- There is a bug that happens when the terms are removed from the approved term list - the user is asked to confirm term removal multiple times
- The phenotypic feature detail pane (right part of the screen) should show the details of the selected item to allow adjustments.



Please ask me to re-review afterwards so that I receive a notification.

Thanks & cheers! :)

**Review by ielis — COMMENTED** [review]
Hey, the 3rd issue is still unresolved on my end. Do you know why I have to click >1 times to remove an item from the table?

https://user-images.githubusercontent.com/12170955/209976700-f9e4214f-da3d-49b9-9993-8909ffa0b332.mp4

**Comment by belkassaby** [comment]
@ielis [b7a4f7](https://github.com/TheJacksonLaboratory/PhenopacketLab/pull/98/commits/b7a4f7ce5c0a3c1597de91ec5825a7870b250b28) fixes the multiple confirmation dialog bug. I have pushed the changes to the live site as well.

**Review by ielis — APPROVED** [review]
Hi @belkassaby , the app works great, thanks a lot!

**Comment by belkassaby** [comment]
thks!! @ielis before I merge this PR, do you have any feedback with the new profile selection?

**Pull request merged**
